### ISSUE TITLE
Error when building composite map with zero significantly enriched attributes

### ISSUE THREAD

**Issue by jrrmzz** [baryshnikova-lab/safe-java#3]
If you build an enrichment landscape where no attributes are significantly enriched, you will get an error when you attempt to build a composite map.

@abarysh Should we disable steps 3/4 in this case?

**Comment by abarysh** [comment]
Yeah, but ideally, the user would get a message about why steps 3 and 4 are not available. So how about leaving the button active but then popping out a message (and not proceeding to steps 3/4) if no attributes are enriched?
