### ISSUE TITLE
SAFE on map wo/ edges 

### ISSUE THREAD

**Issue by cscheeder** [baryshnikova-lab/safe-java#4]
Not really an issue but rather a question: is it possible to use SAFE on a layout with nodes yet without edges? SAFE runs in this case but does not find any enrichments. So I am wodering whether SAFE it's not working in this case  (because I am having the wrong setting or because I am violating some assumptions) or whether I simply don't have any enrichments in my data set (I do however expect some enrichments). 

Thank you in advance,
Christian

**Comment by abarysh** [comment]
Hi Christian,
In principle, yes, absolutely, it's possible. An example is Fig. 3 in a preprint we posted recently: https://www.biorxiv.org/content/10.1101/2022.12.22.521593v1 Here, a version of SAFE was applied to a UMAP projection. The key is to choose the right node distance metric and calibrate the parameters properly.
In practice, I'm not sure that the safe-java implementation you're using is flexible enough to do it. Would you be open to switching to Python? [safepy](https://github.com/baryshnikova-lab/safepy) is a Python implementation of SAFE that is more flexible and adaptable to specific cases. If you're interested, I'd be happy to guide you through the process. Feel free to email me directly (email available at www.baryshnikova-lab.org).
Anastasia

**Comment by cscheeder** [comment]
Hi Anastasia,
Thank you for your fast and helpful reply! In fact this is exactly what I want to do (tSNE instead of UMAP but same same). I will give safepy a try. Thank you for offering your help which I am happy to come back to.
